# 02/05/2025
# Build "docker build -t unit3dup ." inside the Docker folder first
# Remove "docker images", "docker rmi -f unit3dup:latest"

FROM python:3.11-slim

# Set enviroment
ENV VIRTUAL_ENV=/home/pc/venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# Install dependencies and clean
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        sudo \
        ffmpeg \
        poppler-utils \
        libmediainfo-dev \
        build-essential \
        python3-venv \
        python3-dev \
        && rm -rf /var/lib/apt/lists/*

# Crea il gruppo con ID 1000 e poi l'utente pc
RUN groupadd -g 1000 pc && \
    useradd pc -u 1000 -g 1000 -m -s /bin/bash && \
    echo "parzival ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
    
    
# Set the user
USER pc
WORKDIR /home/pc

# A new virtual env
RUN python3 -m venv $VIRTUAL_ENV

# Activate virtual
RUN . $VIRTUAL_ENV/bin/activate

# Copy .whl in the container
COPY unit3dup-0.8.6-py3-none-any.whl /app/

# Upgrade pip
RUN pip install --upgrade pip

# Install .whl inside the virtual
RUN pip install --no-cache-dir /app/unit3dup-0.8.6-py3-none-any.whl

# Set the entry point ( see pyproject.toml)
ENTRYPOINT ["unit3dup"]