# -*- coding: utf-8 -*-

class Contents:
    def __init__(self, guess_title: str, category: int):
        self.guess_title = guess_title
        self.category = category

contents = [
    # Serie TV (category 2)
    Contents("The Good Wife", 2),
    Contents("Breaking Bad", 2),
    Contents("Stranger Things", 2),
    Contents("The Office", 2),
    Contents("Game of Thrones", 2),
    Contents("Friends", 2),
    Contents("The Mandalorian", 2),
    Contents("The Witcher", 2),
    Contents("The Crown", 2),
    Contents("Narcos", 2),
    Contents("Black Mirror", 2),
    Contents("Sherlock", 2),
    Contents("The Boys", 2),
    Contents("The Umbrella Academy", 2),
    Contents("Westworld", 2),
    Contents("The Walking Dead", 2),
    Contents("Money Heist", 2),
    Contents("Vikings", 2),
    Contents("Dexter", 2),
    Contents("Better Call Saul", 2),
    Contents("Fargo", 2),
    Contents("The Simpsons", 2),
    Contents("The Haunting of Hill House", 2),
    Contents("Peaky Blinders", 2),
    Contents("Chernobyl", 2),
    Contents("True Detective", 2),
    Contents("The X-Files", 2),
    Contents("The Sopranos", 2),
    Contents("Twin Peaks", 2),
    Contents("The Office (UK)", 2),
    Contents("Parks and Recreation", 2),
    Contents("Supernatural", 2),
    Contents("House of Cards", 2),
    Contents("Doctor Who", 2),
    Contents("Castle", 2),
    Contents("Mad Men", 2),
    Contents("The Big Bang Theory", 2),
    Contents("How I Met Your Mother", 2),
    Contents("The Flash", 2),
    Contents("Arrow", 2),
    Contents("Daredevil", 2),
    Contents("Luke Cage", 2),
    Contents("Jessica Jones", 2),
    Contents("Agents of S.H.I.E.L.D.", 2),
    Contents("Gotham", 2),
    Contents("The Punisher", 2),
    Contents("Orange is the New Black", 2),
    Contents("Luther", 2),
    Contents("Mindhunter", 2),
    Contents("The Good Doctor", 2),

    # Film (category 1)
    Contents("The Shawshank Redemption", 1),
    Contents("The Godfather", 1),
    Contents("The Dark Knight", 1),
    Contents("Schindler's List", 1),
    Contents("Pulp Fiction", 1),
    Contents("The Lord of the Rings: The Return of the King", 1),
    Contents("Forrest Gump", 1),
    Contents("Inception", 1),
    Contents("Fight Club", 1),
    Contents("The Matrix", 1),
    Contents("Goodfellas", 1),
    Contents("The Empire Strikes Back", 1),
    Contents("The Lion King", 1),
    Contents("Back to the Future", 1),
    Contents("Star Wars: A New Hope", 1),
    Contents("The Terminator", 1),
    Contents("The Silence of the Lambs", 1),
    Contents("Casablanca", 1),
    Contents("Citizen Kane", 1),
    Contents("Schindler's List", 1),
    Contents("Gladiator", 1),
    Contents("Braveheart", 1),
    Contents("The Dark Knight Rises", 1),
    Contents("Jaws", 1),
    Contents("The Shining", 1),
    Contents("A Beautiful Mind", 1),
    Contents("Saving Private Ryan", 1),
    Contents("The Departed", 1),
    Contents("The Prestige", 1),
    Contents("The Green Mile", 1),
    Contents("The Pianist", 1),
    Contents("The Usual Suspects", 1),
    Contents("The Social Network", 1),
    Contents("Interstellar", 1),
    Contents("12 Angry Men", 1),
    Contents("Pulp Fiction", 1),
    Contents("The Godfather: Part II", 1),
    Contents("The Revenant", 1),
    Contents("Django Unchained", 1),
    Contents("Whiplash", 1),
    Contents("The Great Gatsby", 1),
    Contents("Parasite", 1),
    Contents("The Matrix Reloaded", 1),
    Contents("Se7en", 1),
    Contents("Reservoir Dogs", 1),
    Contents("The Lion King", 1),
    Contents("The Godfather Part III", 1)
]
