import os
import random
import re

game_titles = [
    "The Legend of Zelda: Breath of the Wild",
    "Super Mario Odyssey",
    "Red Dead Redemption 2",
    "The Witcher 3: Wild Hunt",
    "Dark Souls III",
    "God of War",
    "Horizon Zero Dawn",
    "Sekiro: Shadows Die Twice",
    "Final Fantasy VII Remake",
    "Cyberpunk 2077",
    "Among Us",
    "Minecraft",
    "Fortnite",
    "Apex Legends",
    "Overwatch",
    "Call of Duty: Warzone",
    "Valorant",
    "Genshin Impact",
    "Assassin's Creed Valhalla",
    "Ghost of Tsushima",
    "Death Stranding",
    "Monster Hunter: World",
    "Resident Evil 2",
    "Doom Eternal",
    "Stardew Valley",
    "Hades",
    "Celeste",
    "Hollow Knight",
    "Ori and the Will of the Wisps",
    "Return of the Obra Dinn",
    "The Last of Us Part II",
    "Control",
    "Ghostrunner",
    "Disco Elysium",
    "Spiritfarer",
    "NieR: Automata",
    "Cuphead",
    "Bioshock Infinite",
    "Darkest Dungeon",
    "The Outer Worlds",
    "Fallout 76",
    "Borderlands 3",
    "Gears 5",
    "Forza Horizon 4",
    "Gran Turismo Sport",
    "FIFA 21",
    "NBA 2K21",
    "Madden NFL 21",
    "The Sims 4",
    "Animal Crossing: New Horizons",
    "Splatoon 2",
    "Mario Kart 8 Deluxe",
    "Street Fighter V",
    "Tekken 7",
    "Mortal Kombat 11",
    "Final Fantasy XIV",
    "World of Warcraft",
    "Destiny 2",
    "Rainbow Six Siege",
    "Battlefield V",
    "Fall Guys: Ultimate Knockout",
    "Ghost Recon Breakpoint",
    "The Division 2",
    "State of Decay 2",
    "Monster Hunter Rise",
    "Dying Light",
    "Far Cry 5",
    "Just Cause 4",
    "Watch Dogs: Legion",
    "CyberConnect2's FFXV",
    "The Evil Within 2",
    "Outlast 2",
    "Amnesia: Rebirth",
    "Dead by Daylight",
    "Resident Evil Village",
    "Until Dawn",
    "The Walking Dead: The Final Season",
    "Life is Strange 2",
    "Detroit: Become Human",
    "Tales from the Borderlands",
    "Firewatch",
    "Oxenfree",
    "The Stanley Parable",
    "What Remains of Edith Finch",
    "The Witness",
    "Journey",
    "Gris",
    "Subnautica",
    "Outer Wilds",
    "Slay the Spire",
    "Factorio",
    "Cities: Skylines",
    "Planet Coaster",
    "Satisfactory",
    "Kerbal Space Program",
    "No Man's Sky",
    "Starbound",
    "Terraria",
    "RimWorld",
    "Oxygen Not Included",
    "Hollow Knight",
    "Dead Cells",
    "Hades",
    "Binding of Isaac: Rebirth",
    "Enter the Gungeon",
    "Risk of Rain 2",
    "Darkwood",
    "Soma",
    "Layers of Fear",
    "Little Nightmares",
    "Inside",
    "Limbo",
    "Fez",
    "Celeste",
    "Katana ZERO",
    "A Short Hike",
    "Journey to the Savage Planet",
    "Ghost of Tsushima",
    "Assassin's Creed Odyssey",
    "Resident Evil 3 Remake",
    "Shadow of the Tomb Raider",
    "Marvel's Spider-Man",
    "Spider-Man: Miles Morales",
    "Batman: Arkham Knight",
    "The Last Guardian",
    "Journey",
    "The Legend of Zelda: Ocarina of Time",
    "Metroid Dread",
    "Hollow Knight: Silksong",
    "Fire Emblem: Three Houses",
    "Persona 5 Royal",
    "Final Fantasy XV",
    "Dragon Quest XI",
    "Xenoblade Chronicles 2",
    "Nioh 2",
    "Sekiro: Shadows Die Twice",
    "Dark Souls II",
    "Bloodborne",
    "The Surge 2",
    "Demon's Souls",
    "Control: Ultimate Edition",
    "Mass Effect Legendary Edition",
    "Bioshock: The Collection",
    "Dying Light 2",
    "Star Wars Jedi: Fallen Order",
    "The Callisto Protocol",
    "Elden Ring",
    "Returnal",
    "Ghostwire: Tokyo",
    "Deathloop",
    "Kena: Bridge of Spirits",
    "Forza Horizon 5",
    "Gran Turismo 7",
    "Hogwarts Legacy",
    "Bayonetta 3",
    "Hellblade II: Senua's Saga",
    "Fable IV",
    "The Elder Scrolls VI",
    "Starfield",
    "Hollow Knight: Silksong",
    "Final Fantasy XVI",
    "God of War: Ragnarök",
    "Tales of Arise",
    "Monster Hunter Stories 2",
    "The Legend of Zelda: Skyward Sword HD",
    "Metroid Prime 4",
    "Splatoon 3",
    "Mario + Rabbids Sparks of Hope",
    "Mario Strikers: Battle League",
    "Xenoblade Chronicles 3",
    "Bayonetta Origins: Cereza and the Lost Demon",
    "FIFA 22",
    "NBA 2K22",
    "Madden NFL 22",
    "WWE 2K Battlegrounds",
    "Need for Speed: Hot Pursuit Remastered",
    "Gran Turismo Sport",
    "F1 2021",
    "Tony Hawk's Pro Skater 1+2",
    "Watch Dogs: Legion",
    "Cyberpunk 2077",
    "Fallout 76",
    "The Outer Worlds",
    "Doom Eternal",
    "Wolfenstein: Youngblood",
    "Resident Evil 3",
    "Resident Evil 2",
    "The Evil Within",
    "Dead Space",
    "Fear & Hunger",
    "Outlast",
    "Soma",
    "Amnesia: The Dark Descent",
    "Layers of Fear",
    "Little Nightmares II",
    "Ghost of Tsushima: Director's Cut",
    "CyberConnect2's Naruto RPG",
    "Dragon Ball Z: Kakarot",
    "One Piece: Pirate Warriors 4",
    "My Hero One's Justice 2",
    "Guilty Gear -Strive-",
    "Street Fighter VI",
    "Tekken 8",
    "SoulCalibur VI",
    "Mortal Kombat 11",
    "Injustice 2",
    "BlazBlue: Central Fiction",
    "Granblue Fantasy: Versus",
    "Melty Blood: Type Lumina",
    "Dengeki Bunko: Fighting Climax",
    "Naruto Shippuden: Ultimate Ninja Storm 4",
    "Persona 4 Arena Ultimax",
    "Kingdom Hearts III",
    "Final Fantasy VII Remake Intergrade",
    "Tales of Berseria",
    "Tales of Vesperia: Definitive Edition",
    "Fire Emblem: Fates",
    "Fire Emblem: Awakening",
    "The Legend of Heroes: Trails of Cold Steel IV",
    "Xenoblade Chronicles Definitive Edition",
    "Nier Replicant ver.1.22474487139...",
    "The Legend of Heroes: Trails in the Sky",
    "Ys IX: Monstrum Nox",
    "Monster Hunter: Rise",
    "Persona 5 Strikers",
    "Code Vein",
    "Dark Souls Remastered",
    "Nioh",
    "Sekiro: Shadows Die Twice",
    "Ghost of Tsushima",
    "Bloodborne",
    "The Surge",
    "Demon's Souls Remake",
    "Dragon's Dogma: Dark Arisen",
    "Elden Ring",
    "Hollow Knight",
    "Spiritfarer",
    "Celeste",
    "Ori and the Blind Forest",
    "Unravel",
    "Gris",
    "Journey",
    "Firewatch",
    "Oxenfree",
    "What Remains of Edith Finch",
    "The Stanley Parable",
    "Inside",
    "Limbo",
    "Braid",
    "Fez",
    "A Short Hike",
    "Little Nightmares",
    "Darkest Dungeon",
    "Slay the Spire",
    "Factorio",
    "RimWorld",
    "Oxygen Not Included",
    "Terraria",
    "Stardew Valley",
    "No Man's Sky",
    "Subnautica",
    "Kerbal Space Program",
    "Cities: Skylines",
    "Planet Coaster",
    "Satisfactory",
    "Hollow Knight: Silksong",
    "Cuphead",
    "Dead Cells",
    "Enter the Gungeon",
    "Risk of Rain 2",
    "Hades",
    "The Binding of Isaac: Rebirth",
    "Spelunky 2",
    "Moon Hunters",
    "Moonlighter",
    "Hollow Knight",
    "Celeste",
    "Little Nightmares II",
    "Hellblade: Senua's Sacrifice",
    "Ori and the Will of the Wisps",
    "Spiritfarer",
    "The Last Guardian",
    "Ghost of Tsushima",
    "Shadow of the Colossus",
    "The Legend of Zelda: Wind Waker HD",
    "Final Fantasy X/X-2 HD Remaster",
    "Chrono Trigger",
    "Persona 5",
    "The Witcher 3: Wild Hunt",
    "Dark Souls III",
    "Bloodborne",
    "The Elder Scrolls V: Skyrim",
    "Mass Effect 2",
    "Dragon Age: Inquisition",
    "Darkest Dungeon",
    "Celeste",
    "Hades",
    "Undertale",
    "Stardew Valley",
    "Hollow Knight",
    "Journey",
    "Firewatch",
    "Oxenfree",
    "The Stanley Parable",
    "What Remains of Edith Finch",
    "The Outer Worlds",
    "Cyberpunk 2077",
    "Doom Eternal",
    "Red Dead Redemption 2",
    "God of War",
    "Final Fantasy VII Remake",
    "Assassin's Creed Valhalla",
    "Watch Dogs: Legion",
    "Spider-Man: Miles Morales",
    "Resident Evil Village",
    "Deathloop",
    "Returnal",
    "Ghostwire: Tokyo",
    "Kena: Bridge of Spirits",
    "Elden Ring",
    "Forza Horizon 5",
    "Gran Turismo 7",
    "Halo Infinite",
    "Starfield",
    "Fable IV",
    "Hogwarts Legacy",
    "Metroid Dread",
    "Bayonetta 3",
    "The Legend of Zelda: Breath of the Wild 2",
    "Final Fantasy XVI",
    "Dragon Quest XII",
    "Monster Hunter Rise",
    "Tales of Arise",
    "Fire Emblem: Three Houses",
    "Persona 6",
    "Final Fantasy XIV: Endwalker",
    "World of Warcraft: Shadowlands",
    "The Elder Scrolls VI",
    "Cyberpunk 2078",
    "Dying Light 2",
    "Outlast 3",
    "Dead Space Remake",
    "Silent Hill: Ascension",
    "Alan Wake 2",
    "Resident Evil 4 Remake",
    "The Callisto Protocol",
    "S.T.A.L.K.E.R. 2",
    "System Shock Remake",
    "Dead Island 2",
    "Hogwarts Legacy",
    "Marvel's Wolverine",
    "Star Wars: Eclipse",
    "Final Fantasy VII Rebirth",
    "Ghost of Tsushima: Director's Cut",
    "Tales of Luminaria",
    "Xenoblade Chronicles 3",
    "Monster Hunter Stories 2",
    "Gran Turismo 7",
    "Forza Horizon 5",
    "F1 2021",
    "NBA 2K22",
    "Madden NFL 22",
    "WWE 2K Battlegrounds",
    "Need for Speed: Hot Pursuit Remastered",
    "Tony Hawk's Pro Skater 1+2",
    "Far Cry 6",
    "Watch Dogs: Legion",
    "Cyberpunk 2077",
    "Fallout 76",
    "Dying Light",
    "Resident Evil 7",
    "Outlast",
    "Amnesia: The Dark Descent",
    "Little Nightmares",
    "Layers of Fear",
    "The Evil Within",
    "Fear & Hunger",
    "Ghost of Tsushima",
    "The Last of Us Part II",
    "Horizon Zero Dawn",
    "Sekiro: Shadows Die Twice",
    "Bloodborne",
    "The Witcher 3: Wild Hunt",
    "Final Fantasy XV",
    "Nioh 2",
    "Dragon Quest XI",
    "Persona 5",
    "Dark Souls III",
    "The Elder Scrolls V: Skyrim",
    "Mass Effect Legendary Edition",
    "Bioshock: The Collection",
    "Persona 4 Golden",
    "Final Fantasy X/X-2 HD Remaster",
    "Chrono Trigger",
    "Tales of Berseria",
    "Fire Emblem: Fates",
    "Xenoblade Chronicles",
    "Nier: Automata",
    "Divinity: Original Sin II",
    "Hades",
    "Stardew Valley",
    "Terraria",
    "No Man's Sky",
    "Factorio",
    "Cities: Skylines",
    "Planet Coaster",
    "RimWorld",
    "Oxygen Not Included",
    "Satisfactory",
    "Kerbal Space Program",
    "Ghost of Tsushima",
    "Death Stranding",
    "Cyberpunk 2077",
    "The Outer Worlds",
    "Doom Eternal",
    "Hollow Knight",
    "Celeste",
    "Undertale",
    "Disco Elysium",
    "What Remains of Edith Finch",
    "Firewatch",
    "Oxenfree",
    "Journey",
    "A Short Hike",
    "Little Nightmares",
    "Gris",
    "Journey to the Savage Planet",
    "Spiritfarer",
    "The Last Guardian",
    "The Legend of Zelda: Skyward Sword HD",
    "The Legend of Zelda: Ocarina of Time",
    "Final Fantasy VII Remake",
    "God of War: Ragnarök",
    "Metroid Dread",
    "Bayonetta 3",
    "Final Fantasy XVI",
    "Hogwarts Legacy",
    "Dragon Quest XII",
    "Xenoblade Chronicles 3",
    "Tales of Arise",
    "Monster Hunter Rise",
    "Dying Light 2",
    "Cyberpunk 2078",
    "Outlast 3",
    "Alan Wake 2",
    "S.T.A.L.K.E.R. 2",
    "System Shock Remake",
    "Dead Space Remake",
    "Silent Hill: Ascension",
    "Marvel's Wolverine",
    "Star Wars: Eclipse",
    "Ghostwire: Tokyo",
    "Deathloop",
    "Kena: Bridge of Spirits",
    "Hollow Knight: Silksong",
    "Final Fantasy XIV: Endwalker",
    "World of Warcraft: Shadowlands",
    "The Elder Scrolls VI",
    "Gran Turismo 7",
    "Forza Horizon 5",
    "F1 2021",
    "Tony Hawk's Pro Skater 1+2",
    "Need for Speed: Hot Pursuit Remastered",
    "NBA 2K22",
    "Madden NFL 22",
    "WWE 2K Battlegrounds",
    "Far Cry 6",
    "Watch Dogs: Legion",
    "Cyberpunk 2077",
    "The Last of Us Part II",
    "The Witcher 3: Wild Hunt",
    "Final Fantasy XV",
    "Nioh 2",
    "Dragon Quest XI",
    "Persona 5",
    "Dark Souls III",
    "The Elder Scrolls V: Skyrim",
    "Mass Effect Legendary Edition",
    "Bioshock: The Collection",
    "Persona 4 Golden",
    "Final Fantasy X/X-2 HD Remaster",
    "Chrono Trigger",
    "Tales of Berseria",
    "Fire Emblem: Fates",
    "Xenoblade Chronicles",
    "Nier: Automata",
    "Divinity: Original Sin II",
    "Hades",
    "Stardew Valley",
    "Terraria",
    "No Man's Sky",
    "Factorio",
    "Cities: Skylines",
    "Planet Coaster",
    "RimWorld",
    "Oxygen Not Included",
    "Satisfactory",
    "Kerbal Space Program",
]

genres = ["Azione", "Avventura", "RPG", "Simulazione", "Sport", "Strategia", "Puzzle"]
developers = ["Developer A", "Developer B", "Developer C", "Developer D", "Developer E"]
publishers = ["Publisher A", "Publisher B", "Publisher C", "Publisher D", "Publisher E"]
modes = ["Singolo giocatore", "Multiplayer", "Co-op"]

crew_patterns = [
    "VENOM",
    "nogrp",
    "LiGHTFORCE",
    "SUXXORS",
    "HR",
    "NiiNTENDO",
    "GANT",
    "BREWS",
    "REPACK-Kaos",
    "GOG",
    "TENOKE",
    "rG",
    "I Know",
    "Razor1911",
    "RUNE",
    "FitGirl Repack",
    "DODI Repack",
    "ElAmigos",
    "RazorDOX",
    "RAZOR",
    "SKIDROW",
    "DINOByTES",
    "TiNYiSO",
    "FCKDRM",
    "FLT",
    "Unleashed",
    "PS4",
    "PS5",
    "I_KnoW",
    "CPY",
    "RELOADED",
    "HATRED",
    "GHOST",
    "HIVE",
    "VACE",
    "DARKSIDERS",
    "P2P",
    "Fallen",
    "NIGHTMARE",
    "PROPHET",
    "C0d3s",
    "SQUiRE",
    "YASU",
    "0xDEADBEEF",
    "OUTLAWS",
    "MACHINE",
    "S0B",
    "Psycho",
    "GAMERS",
    "D3V",
    "DREAM",
    "NEO",
    "TRiViUM",
    "XFORCE",
    "2h4u",
    "COLLATERAL",
    "TRC",
    "n0m",
    "FATE",
    "AGGREGATE",
    "LIG",
    "GAMERZ",
    "SPAWN",
    "CZW",
    "QUACKER",
    "Toxic",
    "D4",
    "RESPECT",
    "XTEAM",
    "Xtreme",
    "X-DiE",
    "D3AD",
    "SQUAD",
    "GAMER",
    "D2R",
    "EQUINOX",
    "TEAM RIPPERS",
    "SICK",
    "PLATINUM",
    "VALHALLA",
    "ZTEAM",
    "SKYNET",
    "JOKER",
    "PRODIGY",
    "NINJA",
    "VOLT",
    "AZURE",
    "BLAZE",
    "KILLER",
    "TITAN",
    "SCARECROW",
    "FIRE",
    "DEMON",
    "RAPID",
    "ALPHA",
    "SILVER",
    "SANDMAN",
    "FANTASY",
    "HORIZON",
    "INFERNO",
    "RAVEN",
    "VIGILANTE",
    "VORTEX",
    "FUSION",
    "NEBULA",
    "SHADOW",
    "WARRIOR",
    "SPECTER",
    "HUNTER",
    "MYSTIC",
    "ZODIAC",
    "REBEL",
    "NOVA",
    "BLIZZARD",
    "PHOENIX",
    "COSMOS",
    "DREAMTEAM",
    "GRIFFON",
    "HAWK",
    "THUNDER",
    "SILVERHAWK",
    "MAGNUM",
    "SILENCER",
    "STRIKER",
    "VELOCITY",
    "STORM",
    "OUTCAST",
    "SPARROW",
    "SPIRIT",
    "NIGHTFALL",
    "DUSK",
    "NOVA",
    "HEAVEN",
    "RAVENCLAW",
    "SCARLET",
    "JAGUAR",
    "VELOCITY",
    "POLARIS",
    "ECHO",
    "GLADIATOR",
    "SPECTRUM",
    "WIZARD",
    "FUSION",
    "NEXUS",
    "WARRIOR",
    "LEGEND",
    "DREAMWALKER",
    "DRAGON",
    "SILVERBLADE",
    "DARKFALL",
    "WINDWALKER",
    "DARKNESS",
    "FURY",
    "LIGHTNING",
    "PANTHER",
    "THOR",
    "NEMESIS",
    "DARKWIND",
    "ICE",
    "BANDIT",
    "TIGER",
    "CRIMSON",
    "SILVERFOX",
    "HORIZON",
    "CROSSBONES",
    "VAMPIRE",
    "VINDICATOR",
    "LIGHTBRINGER",
    "STORMBRINGER",
    "FIREWALKER",
    "GHOSTWALKER",
    "GLORY",
    "FAITH",
    "SABER",
    "BLITZ",
    "PRIME",
    "SPECTRUM",
    "SHADOWFANG",
    "FROST",
    "RUNE",
    "MOONSHADOW",
    "FALCON",
    "NIGHTHAWK",
    "REAPER",
    "SPIDER",
    "PHANTOM",
    "VALIANT",
    "STRIDER",
    "KRAKEN",
    "RAGE",
    "MYST",
    "GHOSTFACE",
    "CROSSHAIR",
    "GLORYHOUND",
    "SILVERBIRD",
    "DRAGONFLY",
    "DUSTWALKER",
    "LIONHEART",
    "TWILIGHT",
    "KINGSFOLK",
    "TURBO",
    "OVERRIDE",
    "REBEL",
    "MOONLIGHT",
    "PREDATOR",
    "FORCE",
    "JOKER",
    "VENGEANCE",
    "BLADE",
    "MIRAGE",
    "HORIZON",
    "MYSTIC",
    "RIDER",
    "MAVERICK",
    "PHOENIX",
    "CHAOS",
    "SPECTRE",
    "WRAITH",
    "SHRIEK",
    "FIREBIRD",
    "MONARCH",
    "VALKYRIE",
    "BLACKHAWK",
    "STEALTH",
    "FIRESTORM",
    "ICICLE",
    "BLADEFURY",
    "NIGHTSTALKER",
    "DREAD",
    "MOONFALL",
    "DRACULA",
    "FALCON",
    "GOLIATH",
    "NITRO",
    "SCARAB",
    "BANSHEE",
    "NIGHTRIDER",
    "JAGUAR",
]

platform_patterns = [
    "LIN",
    "LINUX",
    "N64",
    "WII",
    "PC",
    "PS1",
    "PS2",
    "PS3",
    "XBX",
    "X360",
    "DOS",
    "MAC",
    "C64",
    "AMIGA",
    "NES",
    "SNES",
    "NDS",
    "NGC",
    "GBC",
    "DC",
    "GBA",
    "CPC",
    "ZX",
    "MSX",
    "MD",
    "32X",
    "SAT",
    "GB",
    "AND",
    "GG",
    "XBLA",
    "3DS",
    "PSP",
    "IOS",
    "WIIU",
    "NGAGE",
    "TZ",
    "PSN",
    "VITA",
    "VC",
    "PS4",
    "XBO",
    "3DO",
    "FDS",
    "ARC",
    "MSX2",
    "MOB",
    "WIIW",
    "WS",
    "SFC",
    "A2600",
    "A7800",
    "AL",
    "AJ",
    "AS",
    "SMS",
    "A8",
    "A5200",
    "INT",
    "CV",
    "BBC",
    "VEC",
    "VIC",
    "OUYA",
    "BB",
    "WP",
    "II",
    "X1",
    "SCD",
    "NGM",
    "NGA",
    "WEB",
    "SG",
    "DM30",
    "TG16",
    "VB",
    "ODY",
    "MV",
    "PET",
    "BA",
    "STEAM",
    "C16",
    "CPLUS",
    "P1",
    "P10",
    "P8",
    "GT40",
    "FAMICOM",
    "ANA",
    "NIM",
    "EDSAC",
    "P7",
    "HP2100",
    "HP3000",
    "SIGMA7",
    "CALL",
    "P11",
    "CDC70",
    "PLATO",
    "IMLAC",
    "MC",
    "ONLIVE",
    "CD32",
    "IIGS",
    "ACORN",
    "CDI",
    "FMTOWNS",
    "NGP",
    "NGPC",
    "X68000",
    "NUON",
    "WSC",
    "SWC",
    "PC8801",
    "TRS80",
    "FCF",
    "PCSX",
    "TI99",
    "NSW",
    "NPS",
    "AFTV",
    "V7000",
    "ELECTRON",
    "NG64",
    "NGCD",
    "N3DS",
    "VC4000",
    "APVS",
    "AY8500",
    "AY8610",
    "PC50X",
    "AY8760",
    "AY8710",
    "AY8603",
    "AY8605",
    "AY8606",
    "AY8607",
    "PC98",
    "TGCD",
    "TRS80C",
    "FM7",
    "DRAGON",
    "PCW",
    "EINSTEIN",
    "MO5",
    "PC6000",
    "CDTV",
    "DSI",
    "ESHOP",
    "MR",
    "OCULUS",
    "STEAMVR",
    "DAYDREAM",
    "PSVR",
    "PKMN",
    "XONE",
]

suffixes = [
    "",
    " - Complete Edition",
    " - Game of the Year Edition",
    " - Deluxe Edition",
    " - DLC",
    " - Expansion Pack",
    " - Definitive Edition",
    " - Remastered",
    " - Ultimate Edition",
    " - Collector's Edition",
]


def clean_folder_name(name):
    return re.sub(r'[<>:"/\\|?*]', "", name).replace(" ", ".")


def format_crew_name(name):
    return name.replace(" ", "_")


root_folder = os.path.join(os.path.expanduser("~"), "Downloads", "gametest")

for title in game_titles:
    suffix = random.choice(suffixes)
    game_title_with_suffix = title + suffix

    crew_name = random.choice(crew_patterns)
    platform_name = random.choice(platform_patterns)

    game_info = {
        "title": game_title_with_suffix,
        "genre": "Action",
        "year": "2022",
        "developer": "Developer Name",
        "publisher": "Publisher Name",
        "mode": "Single Player",
        "platform": platform_name,
        "crew": crew_name,
    }

    folder_name = (
            clean_folder_name(game_info["title"])
            + "."
            + clean_folder_name(game_info["platform"])
            + "."
            + format_crew_name(
        game_info["crew"]
    )
    )
    folder_path = os.path.join(root_folder, folder_name)
    os.makedirs(folder_path, exist_ok=True)

    file_content = (
        f"Titolo: {game_info['title']}\n"
        f"Genere: {game_info['genre']}\n"
        f"Anno: {game_info['year']}\n"
        f"Sviluppatore: {game_info['developer']}\n"
        f"Editore: {game_info['publisher']}\n"
        f"Modalità: {game_info['mode']}\n"
        f"Piattaforma: {game_info['platform']}\n"
        f"Crew: {game_info['crew']}\n"
    )

    file_path = os.path.join(
        folder_path, f"{clean_folder_name(game_info['title'])}.txt"
    )
    with open(file_path, "w") as f:
        f.write(file_content)

print("Finish")
