import os
import random

crews = [
    "MeM.GP",
    "NTb",
    "CAKES",
    "METCON",
    "CtrlHD",
    "PLiSSKEN",
    "KOGi",
    "RARBG",
    "TGx",
    "EVO",
    "QOQ",
    "PALEALE",
]
languages = ["ITA", "ENG", "FRE", "SPA", "GER", "POR"]
resolutions = ["720p", "1080p", "2160p", "480p"]
formats = ["WEB-DL", "BluRay", "WEBRip", "HDTV", "DVDRip"]
sources = [
    "DSNP",
    "NF",
    "AMZN",
    "HMAX",
    "iTunes",
    "HULU",
    "DVD",
    "P2P",
    "RARBG",
    "PirateBay",
    "1337x",
]

titles = [
    "The_Great_Escape",
    "Breaking_Bad",
    "Inception",
    "Friends",
    "The_Dark_Knight",
    "Game_of_Thrones",
    "Interstellar",
    "The_Lord_of_the_Rings",
    "The_Godfather",
    "The_Walking_Dead",
    "The_Big_Bang_Theory",
    "Fight_Club",
    "Pulp_Fiction",
    "Forrest_Gump",
    "The_Matrix",
    "The_Shining",
    "The_Office",
    "Shawshank_Redemption",
    "Star_Wars",
    "The_Mandalorian",
    "Stranger_Things",
    "The_Witcher",
    "The_Boys",
    "Black_Mirror",
    "The_Crown",
    "Peaky_Blinders",
    "Narcos",
    "The_Sopranos",
    "True_Detective",
    "Mindhunter",
    "Better_Call_Saul",
    "The_Expanse",
    "Mad_Men",
    "Vikings",
    "The_Handmaid's_Tale",
    "Chernobyl",
    "Fargo",
    "Westworld",
    "The_Flash",
    "Arrow",
    "Daredevil",
    "Jessica_Jones",
    "Luke_Cage",
    "Iron_Fist",
    "The_Defenders",
    "The_Punisher",
    "Rick_and_Morty",
    "BoJack_Horseman",
    "South_Park",
    "Family_Guy",
    "The_Simpsons",
    "Futurama",
    "Brooklyn_Nine-Nine",
    "How_I_Met_Your_Mother",
    "Parks_and_Recreation",
    "House_of_Cards",
    "Orange_Is_the_New_Black",
    "Ozark",
    "Lucifer",
    "Supernatural",
    "Grey's_Anatomy",
    "The_Wire",
    "Lost",
    "Prison_Break",
    "Heroes",
    "Breaking_Bad_El_Camino",
    "Elita",
    "Casa_de_Papel",
    "Titanic",
    "Joker",
    "Parasite",
    "The_Irishman",
    "Ford_v_Ferrari",
    "Jojo_Rabbit",
    "1917",
    "Knives_Out",
    "Marriage_Story",
    "Once_Upon_a_Time_in_Hollywood",
    "Ad_Astra",
    "Rocketman",
    "Jumanji",
    "Toy_Story_4",
    "Spider-Man_Far_From_Home",
    "Frozen_II",
    "The_Lion_King",
    "Aladdin",
    "Avengers_Endgame",
    "Captain_Marvel",
    "Shazam",
    "Aquaman",
    "Wonder_Woman",
    "Justice_League",
    "The_Batman",
    "Suicide_Squad",
    "Deadpool",
    "Logan",
    "X-Men_Dark_Phoenix",
    "Fantastic_Beasts",
    "Harry_Potter",
    "Twilight",
    "The_Hunger_Games",
    "Divergent",
    "Maze_Runner",
    "The_Maze_Runner_2",
    "Mission_Impossible",
    "James_Bond_No_Time_to_Die",
    "Skyfall",
    "Casino_Royale",
    "Spectre",
    "Die_Another_Day",
    "Fast_and_Furious_9",
    "Hobbs_and_Shaw",
    "John_Wick",
    "The_Bourne_Identity",
    "Taken",
    "The_Equalizer",
    "Mad_Max_Fury_Road",
    "The_Road_Warrior",
    "Terminator_2",
    "Alien",
    "Aliens",
    "Predator",
    "Predator_2",
    "The_Mummy",
    "Indiana_Jones",
    "Jurassic_Park",
    "Jurassic_World",
    "King_Kong",
    "Godzilla",
    "Pacific_Rim",
    "Transformers",
    "The_Dark_Knight_Rises",
    "Batman_Begins",
    "Spider-Man",
    "The_Amazing_Spider-Man",
    "The_Incredible_Hulk",
    "Thor",
    "Iron_Man",
    "The_Avengers",
    "Guardians_of_the_Galaxy",
    "Doctor_Strange",
    "Black_Panther",
    "Ant-Man",
    "Captain_America_Civil_War",
    "Captain_America_The_Winter_Soldier",
    "Hannibal",
    "The_Silence_of_the_Lambs",
    "Seven",
    "Zodiac",
    "Gone_Girl",
    "Fight_Club",
    "The_Game",
    "Memento",
    "The_Prestige",
    "Dunkirk",
    "Tenet",
    "The_Imitation_Game",
    "The_Theory_of_Everything",
    "A_Beautiful_Mind",
    "The_Social_Network",
    "The_Wolf_of_Wall_Street",
    "Catch_Me_If_You_Can",
    "The_Terminal",
    "Cast_Away",
    "Saving_Private_Ryan",
    "Apollo_13",
    "The_Green_Mile",
    "Shawshank_Redemption",
    "Million_Dollar_Baby",
    "Gran_Torino",
    "Unforgiven",
    "Django_Unchained",
    "Inglourious_Basterds",
    "Pulp_Fiction",
    "Kill_Bill",
    "Reservoir_Dogs",
    "The_Hateful_Eight",
    "No_Country_for_Old_Men",
    "Fargo",
    "There_Will_Be_Blood",
    "Gangs_of_New_York",
    "The_Departed",
    "Goodfellas",
    "Casino",
    "Taxi_Driver",
    "Raging_Bull",
    "The_Irishman",
    "Scarface",
    "The_Untouchables",
    "Heat",
    "The_Town",
    "Gone_Baby_Gone",
    "Mystic_River",
    "The_Departed",
    "American_Sniper",
    "Gran_Torino",
    "Flags_of_Our_Fathers",
    "Letters_from_Iwo_Jima",
    "Dunkirk",
    "Saving_Private_Ryan",
    "Black_Hawk_Down",
    "The_Hurt_Locker",
    "Zero_Dark_Thirty",
    "13_Hours",
    "Lone_Survivor",
    "Act_of_Valor",
    "The_Pianist",
    "Schindler's_List",
    "Life_is_Beautiful",
    "The_Boy_in_the_Striped_Pajamas",
    "The_Imitation_Game",
    "The_Theory_of_Everything",
    "The_King's_Speech",
    "Darkest_Hour",
    "Lincoln",
    "The_Post",
    "Spotlight",
    "Moonlight",
    "La_La_Land",
    "Whiplash",
    "Birdman",
    "The_Revenant",
    "Gravity",
    "Interstellar",
    "The_Martian",
    "Blade_Runner_2049",
    "Arrival",
    "Edge_of_Tomorrow",
    "Oblivion",
    "Elysium",
    "District_9",
    "Chappie",
    "Avatar",
    "Aliens",
    "Prometheus",
    "Alien_Covenant",
    "The_Matrix",
    "Matrix_Reloaded",
    "Matrix_Revolutions",
    "Dune",
    "Star_Wars_A_New_Hope",
    "The_Empire_Strikes_Back",
    "Return_of_the_Jedi",
    "The_Force_Awakens",
    "The_Last_Jedi",
    "Rise_of_Skywalker",
    "Rogue_One",
    "Solo",
    "The_Mandalorian",
    "The_Book_of_Boba_Fett",
    "Obi_Wan_Kenobi",
    "Ahsoka",
    "Andor",
]


def generate_season_episode():
    season = f"S{random.randint(1, 10):02}"  # Stagioni da 1 a 10
    episode = f"E{random.randint(1, 24):02}"  # Episodi da 1 a 24
    return f"{season}{episode}"


def generate_folder_name(title):
    crew_sample_size = min(
        len(crews), random.randint(1, 3)
    )
    selected_crews = random.sample(crews, crew_sample_size)

    language_sample_size = min(
        len(languages), random.randint(1, 2)
    )
    selected_languages = random.sample(languages, language_sample_size)

    resolution = random.choice(resolutions)
    video_format = random.choice(formats)
    source = random.choice(sources)

    if "Title_" in title:
        season_episode = generate_season_episode()
        folder_name = f"{title}.{season_episode}.{'.'.join(selected_languages)}.{resolution}.{source}.{video_format}.{'.'.join(selected_crews)}"
    else:
        folder_name = f"{title}.{'.'.join(selected_languages)}.{resolution}.{source}.{video_format}.{'.'.join(selected_crews)}"

    return folder_name


base_path = os.path.join(os.path.expanduser("~"), "Downloads", "videotest")


def create_folders_with_files(titles):
    if not os.path.exists(base_path):
        os.makedirs(base_path)

    for title in titles:
        folder_name = generate_folder_name(title)
        folder_path = os.path.join(base_path, folder_name)

        os.makedirs(folder_path, exist_ok=True)

        fake_file_path = os.path.join(folder_path, f"{folder_name}.mkv")
        with open(fake_file_path, "w") as fake_file:
            fake_file.write("This is a dummy MKV file.")


create_folders_with_files(titles)
