# -*- coding: utf-8 -*-

itt_data = {
    "CATEGORY": {"movie": 1, "tvshow": 2, "edicola": 7, "game": 4},
    "FREELECH": {"size20": 100, "size15": 75, "size10": 50, "size5": 25},
    "TYPE_ID": {
        "full-disc": 1,
        "remux": 2,
        "bdremux": 2,
        "vh": 2,
        "untouched": 2,
        "bd-untouched": 2,
        "encode": 3,
        "bluray": 3,
        "fullhd": 3,
        "hvec": 3,
        "vu": 3,
        "hdrip": 3,
        "web-dl": 4,
        "webdl": 4,
        "web": 4,
        "web-dlmux": 4,
        "webrip": 5,
        "hdtv": 6,
        "flac": 7,
        "alac": 8,
        "ac3": 9,
        "aac": 10,
        "mp3": 11,
        "mac": 12,
        "windows": 13,
        "cinema-md": 14,
        "hdts": 14,
        "wrs": 14,
        "md": 14,
        "altro": 15,
        "pdf": 16,
        "nintendo": 17,
        "ps4": 18,
        "epub": 19,
        "mp4": 20,
        "pack": 21,
        "avi": 22,
        "dvdrip": 23,
        "bdrip": 24,
        "webmux": 25,
        "dlmux": 26,
        "bdmux": 27,
        "3d": 28,
        "cbr-cbz": 29,
        "ps5": 30,
    },
    "TAGS": {
        "SD": 1,
        "HD": 0,
    },
    "RESOLUTION": {
        "4320p": 1,
        "2160p": 2,
        "1080p": 3,
        "1080i": 4,
        "720p": 5,
        "576p": 6,
        "576i": 7,
        "480p": 8,
        "480i": 9,
        "altro": 10,
    },
    "CODEC": [
        "h261",
        "h262",
        "h263",
        "h264",
        "x264",
        "x265",
        "avc",
        "h265",
        "hevc",
        "vp8",
        "vp9",
        "av1",
        "mpeg-1",
        "mpeg-4",
        "wmv",
        "theora",
        "divx",
        "xvid",
        "prores",
        "dnxhd",
        "cinepak",
        "indeo",
        "dv",
        "ffv1",
        "sorenson",
        "rv40",
        "cineform",
        "huffyuv",
        "mjpeg",
        "lagarith",
        "msu",
        "rle",
        "dirac",
        "wmv3",
        "vorbis",
        "smpte",
        "mjpeg",
        "ffvhuff",
        "v210",
        "yuv4:2:2",
        "yuv4:4:4",
        "hap",
        "sheervideo",
        "ut",
        "quicktime",
        "rududu",
        "h.266",
        "vvc",
        "mjpeg 4:2:0",
        "h.263+",
        "h.263++",
        "vp4",
        "vp5",
        "vp6",
        "vp7",
        "vp8",
        "vp9",
        "vp10",
        "vp11",
        "vp12",
        "vp3",
        "vp2",
        "vp1",
        "amv",
        "daala",
        "gecko",
        "nvenc",
        "bluray",
    ],
}
