# -*- coding: utf-8 -*-

itt_data = {
    "CATEGORY":{ "movie": 1,
                 "tv": 2,
                 "edicola": 6,
                 "game": 4},

    "FREELECH":{ "size20": 100,
                 "size15": 75,
                 "size10": 50,
                 "size5": 25},

    "TYPE_ID":{ "full-disc": 1,
                "remux": 2,
                "bdremux": 2,
                "vh": 2,
                "untouched": 2,
                "bd-untouched": 2,
                "encode": 3,
                "bluray": 3,
                "fullhd": 3,
                "hevc": 3,
                "hdrip": 3,
                "uhd": 3,
                "vu": 2,
                "web-dl": 4,
                "webdl": 4,
                "web": 4,
                "web-dlmux": 4,
                "webrip": 5,
                "hdtv": 6,
                "mac": 12,
                "macos": 12,
                "windows": 13,
                "pc": 13,
                "cinema-md": 14,
                "hdts": 14,
                "wrs": 14,
                "md": 14,
                "altro": 15,
                "pdf": 16,
                "nintendo": 17,
                "nsw": 17,
                "ps4": 18,
                "psn": 18,
                "epub": 19,
                "mp4": 20,
                "pack": 22,
                "avi": 23,
                "dvdrip": 24,
                "bdrip": 25,
                "webmux": 26,
                "dlmux": 27,
                "bdmux": 29,
                "3d": 32,
                "cbr-cbz": 33,
                "ps5": 35,
                "psvr": 35,
    },
    "TYPE_ID_AUDIO":{ "flac": 7,
                      "alac": 8,
                      "ac3": 9,
                      "aac": 10,
                      "mp3": 11,
    },
    "TAGS":{
             "SD": 1,
             "HD": 0,
    },
    "RESOLUTION": {
                    "4320p": 1,
                    "2160p": 2,
                    "1080p": 3,
                    "1080i": 4,
                    "720p": 5,
                    "576p": 6,
                    "576i": 7,
                    "480p": 8,
                    "480i": 9,
                    "altro": 10,
    },
    "CODEC": [
                "h261",
                "h262",
                "h263",
                "h264",
                "x264",
                "x265",
                "avc",
                "h265",
                "hevc",
                "vp8",
                "vp9",
                "av1",
                "mpeg-1",
                "mpeg-4",
                "wmv",
                "theora",
                "divx",
                "xvid",
                "prores",
                "dnxhd",
                "cinepak",
                "indeo",
                "dv",
                "ffv1",
                "sorenson",
                "rv40",
                "cineform",
                "huffyuv",
                "mjpeg",
                "lagarith",
                "msu",
                "rle",
                "dirac",
                "wmv3",
                "vorbis",
                "smpte",
                "mjpeg",
                "ffvhuff",
                "v210",
                "yuv4:2:2",
                "yuv4:4:4",
                "hap",
                "sheervideo",
                "ut",
                "quicktime",
                "rududu",
                "h.266",
                "vvc",
                "mjpeg 4:2:0",
                "h.263+",
                "h.263++",
                "vp4",
                "vp5",
                "vp6",
                "vp7",
                "vp8",
                "vp9",
                "vp10",
                "vp11",
                "vp12",
                "vp3",
                "vp2",
                "vp1",
                "amv",
                "daala",
                "gecko",
                "nvenc",
                "bluray",
            ],
}
