# -*- coding: utf-8 -*-

ptt_data = {
    "CATEGORY": {
        "applications": 6,
        "audiobooks": 25,
        "ebooks": 20,
        "4Kmovies": 23,
        "movies": 1,
        "games": 5,
        "others": 19,
        "music": 8,
        "sports": 21,
        "TV series": 9,
    },
    "FREELECH": {"size20": 100,
                 "size15": 75,
                 "size10": 50,
                 "size5": 25},
    "TYPE_ID": {
        "bdrip": 11,
        "blu-ray": 16,
        "brrip": 18,
        "dvdrip": 15,
        "discography": 3,
        "encode": 7,
        "flac": 8,
        "full album": 9,
        "full disc": 1,
        "hdtv": 6,
        "others": 12,
        "polish cinema": 20,
        "cinema": 13,
        "cam": 13,
        "webscr": 13,
        "music": 14,
        "remux": 2,
        "sdtv": 17,
        "tvrip": 19,
        "vr": 21,
        "web-dl": 4,
        "pc": 5,
        "pdf": 22,
        "pc games": 23,
        "playstation": 24,
        "xbox": 25,
        "nintendo switch": 26,
        "vr_2": 27,
        "retro": 28,
    },
    "TYPE_ID_AUDIO": {"flac": 8,
                      "mp3": 10,
                      },
    "TAGS": {
        "SD": 1,
        "HD": 0,
    },

    "RESOLUTION": {
        "4320p": 1,
        "2160p": 2,
        "1440p": 12,
        "1080p": 3,
        "1080i": 4,
        "720p": 5,
        "480p": 10,
    },

    "CODEC": [
        "h261",
        "h262",
        "h263",
        "h264",
        "x264",
        "x265",
        "avc",
        "h265",
        "hevc",
        "vp8",
        "vp9",
        "av1",
        "mpeg-1",
        "mpeg-4",
        "wmv",
        "theora",
        "divx",
        "xvid",
        "prores",
        "dnxhd",
        "cinepak",
        "indeo",
        "dv",
        "ffv1",
        "sorenson",
        "rv40",
        "cineform",
        "huffyuv",
        "mjpeg",
        "lagarith",
        "msu",
        "rle",
        "dirac",
        "wmv3",
        "vorbis",
        "smpte",
        "mjpeg",
        "ffvhuff",
        "v210",
        "yuv4:2:2",
        "yuv4:4:4",
        "hap",
        "sheervideo",
        "ut",
        "quicktime",
        "rududu",
        "h.266",
        "vvc",
        "mjpeg 4:2:0",
        "h.263+",
        "h.263++",
        "vp4",
        "vp5",
        "vp6",
        "vp7",
        "vp8",
        "vp9",
        "vp10",
        "vp11",
        "vp12",
        "vp3",
        "vp2",
        "vp1",
        "amv",
        "daala",
        "gecko",
        "nvenc",
        "bluray",
    ],
}
