# -*- coding: utf-8 -*-

sis_data = {
    "CATEGORY": {"movie": 1,
                 "tvshow": 2,
                 "ebook":15,
                 "edicola": 17,
                 "xxx":19,
                 "Music": 3,
                 "game": 7,
                 "software": 23,
                 "eventi sportivi": 24,
                 "misc": 25},

    "FREELECH": {"size20": 100,
                 "size15": 75,
                 "size10": 50,
                 "size5": 25},


    "TYPE_ID": {
                "encode": 15,
                "web": 27,
                "web-dl": 27,
                "webrip": 27,
                "remux": 7,
                "disk": 26,
                "cinemanews": 42,
                "hdtv": 33,
                "window": 31,
                "linux": 39,
                "android": 38,
                "appleos": 32,
                "mp3": 25,
                "flac": 24,
                "epub": 48,
                "pdf": 49,
                "altro": 47,

    },
    "TYPE_ID_AUDIO": {
                "flac": 24,
                "alac": 8,
                "ac3": 9,
                "aac": 10,
                "mp3": 25,
    },
    "TAGS": {
                "SD": 1,
                "HD": 0,
    },
    "RESOLUTION": {
                    "4320p": 1,
                    "2160p": 2,
                    '1440p': 3,
                    "1080p": 3,
                    "1080i": 4,
                    "720p": 5,
                    "576p": 6,
                    "576i": 7,
                    "480p": 8,
                    "480i": 9,
                    "altro": 11,
    },
    "CODEC": [
                "h261",
                "h262",
                "h263",
                "h264",
                "x264",
                "x265",
                "avc",
                "h265",
                "hevc",
                "vp8",
                "vp9",
                "av1",
                "mpeg-1",
                "mpeg-4",
                "wmv",
                "theora",
                "divx",
                "xvid",
                "prores",
                "dnxhd",
                "cinepak",
                "indeo",
                "dv",
                "ffv1",
                "sorenson",
                "rv40",
                "cineform",
                "huffyuv",
                "mjpeg",
                "lagarith",
                "msu",
                "rle",
                "dirac",
                "wmv3",
                "vorbis",
                "smpte",
                "mjpeg",
                "ffvhuff",
                "v210",
                "yuv4:2:2",
                "yuv4:4:4",
                "hap",
                "sheervideo",
                "ut",
                "quicktime",
                "rududu",
                "h.266",
                "vvc",
                "mjpeg 4:2:0",
                "h.263+",
                "h.263++",
                "vp4",
                "vp5",
                "vp6",
                "vp7",
                "vp8",
                "vp9",
                "vp10",
                "vp11",
                "vp12",
                "vp3",
                "vp2",
                "vp1",
                "amv",
                "daala",
                "gecko",
                "nvenc",
                "bluray",
            ],
}
