# -*- coding: utf-8 -*-

TAGS_LIST = {
            "REMUX": "remux",
            "WEB-DL": "source",
            "WEBDL": "source",
            "WEB-DLRIP": "source",
            "WEBDLRIP": "source",
            "WEB-DLMUX": "source",
            "WEBDLMUX": "source",
            "WEBMUX": "source",
            "WEBRIP": "source",
            "BD-UNTOUCHED": "source",
            "UNTOUCHED": "source",

            "TS": "source",
            "CAM": "source",
            "HDTS": "source",
            "MD": "source",
            "UHDRIP": "source",
            "BLURAY": "source",
            "BRRIP": "source",
            "BDRIP": "source",
            "FHDRIP": "source",
            "PDTV": "source",
            "SATRIP": "source",
            "DVBRIP": "source",
            "DVB-S": "source",
            "DTTRIP": "source",
            "WP": "source",
            "DVDSCR": "source",
            "TVRIP": "source",
            "VHSRIP": "source",
            "DVDRIP": "source",
            "HDTV": "source",
            "DVD5": "source",
            "DVD9": "source",
            "VU": "source",

            "ATVP": "platform",
            "AMZN": "platform",
            "AMC": "platform",
            "CN": "platform",
            "CR": "platform",
            "DCU": "platform",
            "DISC": "platform",
            "DSCP": "platform",
            "DSNY": "platform",
            "DSNP": "platform",
            "DPLY": "platform",
            "ESPN": "platform",
            "FOOD": "platform",
            "FOX": "platform",
            "PLAY": "platform",
            "HBO": "platform",
            "HMAX": "platform",
            "HGTV": "platform",
            "HIST": "platform",
            "HULU": "platform",
            "MTOD": "platform",
            "NATG": "platform",
            "NF": "platform",
            "NICK": "platform",
            "NOW": "platform",
            "PMNT": "platform",
            "PMTP": "platform",
            "PCOK": "platform",
            "RKTN": "platform",
            "SHO": "platform",
            "SKST": "platform",
            "STAN": "platform",
            "STRP": "platform",
            "STZ": "platform",
            "TIMV": "platform",

            "SPECIAL": "version",
            "REPACK": "version",
            "EXTENDED": "version",
            "EDITION": "version",
            "DIRECTOR'S": "version",
            "CUT": "version",

            "SUBBED": "version",
            "MUX": "version",
            "REMASTERED": "version",
            "READNFO": "version",
            "UNRATED": "version",
            "UNCUT": "version",
            "LIMITED": "version",
            "ANNIVERSARY": "version",
            "4k RESTORATION": "version",
            "IMAX": "version",
            "OPEN MATTE": "version",
            "2IN1": "version",

            "STV": "version",
            "RECODE": "version",
            "INTERNAL": "version",
            "PROPER": "version",
            "DUAL": "version",
            "COMPLETE": "version",
            "COMPLETA": "version",

            "X264": "video_encoder",
            "X265": "video_encoder",
        }